#!/bin/bash

echo "🎭 HPV Warriors DAO - 12-Minute Judge Demo Script"
echo "==============================================="
echo ""
echo "This script guides you through the complete demo flow."
echo "Follow along in the web interface at http://localhost:3000"
echo ""

read -p "Press Enter to continue..."

echo ""
echo "🏥 STEP 1: Register Clinic (Admin Action)"
echo "----------------------------------------"
echo "1. Navigate to http://localhost:3000/admin"
echo "2. Connect your wallet"
echo "3. Go to 'Clinic Management' tab"
echo "4. Register a clinic address (e.g., your wallet address)"
echo "5. Confirm the transaction"
echo ""
read -p "Complete Step 1, then press Enter..."

echo ""
echo "🛡️ STEP 2: Verify as Guardian"
echo "----------------------------"
echo "1. Navigate to http://localhost:3000/verify"
echo "2. Connect your wallet"
echo "3. Simulate NFC tap (use 'Generate Fake Chip' button)"
echo "4. Generate ZK proof (mock)"
echo "5. Mint Guardian NFT"
echo ""
read -p "Complete Step 2, then press Enter..."

echo ""
echo "💬 STEP 3: Create Anonymous Post"
echo "-------------------------------"
echo "1. Navigate to http://localhost:3000/forum"
echo "2. Click 'Create Post'"
echo "3. Write a sample health question"
echo "4. Submit the post"
echo "5. Verify it appears with Guardian badge"
echo ""
read -p "Complete Step 3, then press Enter..."

echo ""
echo "👍 STEP 4: Upvote from Second Wallet"
echo "----------------------------------"
echo "1. Switch to a different wallet (or use MetaMask account 2)"
echo "2. Find the post you created"
echo "3. Click the upvote button"
echo "4. Confirm the transaction"
echo "5. See the upvote count increase"
echo ""
read -p "Complete Step 4, then press Enter..."

echo ""
echo "🏆 STEP 5: Show Leaderboard"
echo "-------------------------"
echo "1. Navigate to http://localhost:3000/leaderboard"
echo "2. View community statistics"
echo "3. See your address in the rankings"
echo "4. Switch between sorting options (upvotes, posts, rewards)"
echo ""
read -p "Complete Step 5, then press Enter..."

echo ""
echo "🎁 STEP 6: Allocate Rewards"
echo "-------------------------"
echo "1. Go back to http://localhost:3000/admin"
echo "2. Switch to 'Reward Allocation' tab"
echo "3. Add your wallet address and an amount (e.g., 0.1 ETH)"
echo "4. Allocate rewards"
echo "5. Return to leaderboard to see updated rewards"
echo ""
read -p "Complete Step 6, then press Enter..."

echo ""
echo "🎉 Demo Complete!"
echo "================"
echo ""
echo "You've successfully demonstrated:"
echo "✅ Admin clinic registration"
echo "✅ Guardian verification (NFC + ZK)"
echo "✅ Anonymous posting with Guardian badges"
echo "✅ Community upvoting"
echo "✅ Leaderboard tracking"
echo "✅ Reward allocation and display"
echo ""
echo "🔗 Key Technologies Showcased:"
echo "   • Self Protocol (ZK verification) - MOCKED"
echo "   • NFC reading - MOCKED"
echo "   • WalletConnect integration"
echo "   • On-chain events and The Graph indexing - MOCKED"
echo "   • Polygon/World Chain deployment ready"
echo ""
echo "📊 Judge Evaluation Points:"
echo "   • Complete end-to-end flow"
echo "   • Real smart contracts (deployable)"
echo "   • Privacy-first design"
echo "   • Production-ready architecture"
echo "   • Seamless UX with fallbacks"
echo ""
echo "Thank you for trying HPV Warriors DAO! 🎭"